# Site settings
title: David Hayes
email: david@davidhayes.us
description: > # this means to ignore newlines until "baseurl:"
  Portfolio for Full-Stack Web Developer David Hayes from the Chicago Area
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidlhayescreative.com" # the base hostname & protocol for your site
twitter_username: webdevhayes
github_username:  davidlhayes

# Build settings
markdown: kramdown
